from datetime import datetime
from pathlib import Path

Import("env")

project_dir = Path(env["PROJECT_DIR"])
out_file = project_dir / "Grbl_Esp32" / "src" / "BuildInfo.cpp"

# Keep format compatible with existing WebUI parsing: no ':' in the build suffix.
build_stamp = datetime.now().strftime("%b %d %Y-%H%M%S")
content = (
    "// Auto-generated by scripts/gen_build_info.py\n"
    "// Do not edit manually.\n\n"
    f"extern const char* const GRBL_VERSION_BUILD = \"{build_stamp}\";\n"
)

out_file.write_text(content, encoding="ascii")
print(f"[gen_build_info] {build_stamp}")
